# Import Dependencies

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

# Enter data

In [4]:
df = pd.read_csv(r'./iris-data_og.csv')
x = df.iloc[:, :-1]
y = df.iloc[:,-1]

# Split your data

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

# Create Machine Learning Model

In [6]:
rfc = RandomForestClassifier()

# Train Machine Learning Model

In [7]:
model = rfc.fit(x_train, y_train)

# Calculate Accuracy

In [11]:
print(f'Accuracy: { round( model.score( x_test, y_test) * 100, 2) }')
print(f'Confusion Matrix \n { confusion_matrix( y_test, model.predict(x_test) ) }')

Accuracy: 93.33
Confusion Matrix 
 [[ 7  0  0]
 [ 0 13  0]
 [ 0  2  8]]
